apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fma
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
images:
  - name: fma
    newName: ghcr.io/jabberwocky238/fma
    newTag: latest
